name: Feature request
description: Propose an improvement or new capability
title: "[feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the use case first, then the proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What are you trying to do?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should the API/behavior look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or rejected approaches?

  - type: textarea
    id: compatibility
    attributes:
      label: Compatibility impact
      description: Could this break existing users?

